services:

  # App
  app:
    build:
      context: .
      dockerfile: build/docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      TZ: ${APP_TZ}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - digitalExchange


  # Postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: ${APP_TZ}
    ports:
      - ${DB_PORT:-5431}:5432
    volumes:
      - ./build/docker/postgresql/postgres.conf:/etc/postgresql.conf:ro
      - ./build/docker/postgresql/pg_hba.conf:/etc/pg_hba.conf:ro
      - ./build/docker/postgresql/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh:ro
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf", "-c", "hba_file=/etc/pg_hba.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - digitalExchange


# Persistent Volumes
volumes:
  postgres-data:

# Networks
networks:
  digitalExchange:
    driver: bridge