// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"DigitalExchange/src/api/http/controllers"
	"DigitalExchange/src/database"
)

// Injectors from wire.go:

func InitializeServiceContainer() *ServiceContainer {
	databaseDatabase := database.GetInstance()
	exchangeRepository := ProvideExchangeRepository(databaseDatabase)
	exchangeService := ProvideExchangeService(exchangeRepository)
	exchangeController := ProvideExchangeController(exchangeService)
	serviceContainer := &ServiceContainer{
		ExchangeController: exchangeController,
	}
	return serviceContainer
}

// wire.go:

type ServiceContainer struct {
	ExchangeController *controllers.ExchangeController
}
